## OBJETIVO
Criar um modelo de aprendizado de máquina que prevê quem sobreviveu no Titanic

## HIPÓTESES
Pessoas com maior chances de sobrevivência:
- Pessoas da mesma família
- Mulheres
- Crianças
- Pessoas de maior renda / 1a. classe (Pclass)
- Funcionários do navio de alto escalão (capitão)

Pessoas com menor chances de sobrevivencia:
- Sozinhas
- Idosos
- Alocadas em alguma cabine/setor mais longe do bote salva vidas


### colunas incompletas
- Idade
- Cabine

In [17]:
# Import Libraries
import pandas as pd
import matplotlib as plot
import seaborn as sns

In [18]:
# Load file
filepath = r"C:\Users\marco\OneDrive\Documents\CS\Intern\PythonNotebook\bootcampia\ex_titanic\train.csv"
data_frame = pd.read_csv(filepath)

survivalList = r"C:\Users\marco\OneDrive\Documents\CS\Intern\PythonNotebook\bootcampia\ex_titanic\gender_submission.csv"
df_survivalList = pd.read_csv(survivalList)

In [26]:
# Survived Passengers in sample ( 414/891 )
df_survivedPassengers = data_frame[data_frame["Survived"] == 1]
df_survivedPassengers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [20]:
df_womenSurvived = data_frame[(data_frame["Survived"] == 1) & (data_frame["Sex"] == "female")]
df_womenSurvived

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [24]:
df_womenSurvived.count()

PassengerId    233
Survived       233
Pclass         233
Name           233
Sex            233
Age            197
SibSp          233
Parch          233
Ticket         233
Fare           233
Cabin           91
Embarked       231
dtype: int64

In [ ]:
# Gráfico que mostra sobreviventes por gênero

In [ ]:
# Gráfico que mostra sobreviventes por idade

In [27]:
# Gráfico que mostra sobreviventes por gênero e idade